# This is a basic workflow that is manually triggered

name: TriggerPW

on:
  pull_request:
      branches: 
        - main
      
jobs:
  trigger-pw:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger child repo workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: raltunel
          repo: playwright-metamask-gh-action
          ref: master
          github_token: ${{ secrets.MY_TOKEN }}
          workflow_file_name: RunPlaywright.yml
          client_payload: "{\"url\":\"deploy-preview-${{ github.event.number }}--proven-cicd-playground.netlify.app\"}"
          wait_interval: 600
          trigger_workflow: true
          wait_workflow: true
      - name: Echo workflow succeed
        shell: bash
        run: |
          echo "Done man"